-- =====================================================
-- Migration: V3__create_chat_users_table.sql
-- Description: Create users table in chat schema
-- =====================================================

-- Create user_status enum type
CREATE TYPE chat.user_status AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'DELETED');

-- Create users table
CREATE TABLE IF NOT EXISTS chat.users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(256) NOT NULL UNIQUE,
    is_email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    firebase_user_id VARCHAR(100) NOT NULL UNIQUE,
    status chat.user_status NOT NULL DEFAULT 'INACTIVE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP WITH TIME ZONE NULL
);

-- Create indexes
CREATE INDEX idx_users_email ON chat.users(email);
CREATE INDEX idx_users_firebase_user_id ON chat.users(firebase_user_id);
CREATE INDEX idx_users_status ON chat.users(status);

-- Add comment
COMMENT ON TABLE chat.users IS 'Users in chat system';
COMMENT ON COLUMN chat.users.firebase_user_id IS 'Firebase authentication user ID';
COMMENT ON COLUMN chat.users.is_email_verified IS 'Whether user email has been verified';
