-- =====================================================
-- Migration: V7__create_conversation_participants_table.sql
-- Description: Create conversation participants table (optional for future group chat support)
-- =====================================================

-- Create conversation_participants table
CREATE TABLE IF NOT EXISTS chat.conversation_participants (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id INT NOT NULL,
    user_id INT NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    left_at TIMESTAMP WITH TIME ZONE NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    -- Foreign key constraints
    CONSTRAINT fk_conversation_participants_conversation FOREIGN KEY (conversation_id)
        REFERENCES chat.conversations(id) ON DELETE CASCADE,
    CONSTRAINT fk_conversation_participants_user FOREIGN KEY (user_id)
        REFERENCES chat.users(id) ON DELETE CASCADE,

    -- Unique constraint
    CONSTRAINT uq_conversation_user_participant UNIQUE (conversation_id, user_id)
);

-- Create indexes
CREATE INDEX idx_conversation_participants_conversation_id ON chat.conversation_participants(conversation_id);
CREATE INDEX idx_conversation_participants_user_id ON chat.conversation_participants(user_id);
CREATE INDEX idx_conversation_participants_active ON chat.conversation_participants(is_active) WHERE is_active = TRUE;

-- Add comment
COMMENT ON TABLE chat.conversation_participants IS 'Tracks participants in conversations (supports future group chat)';
