-- =====================================================
-- Migration: V2__create_chat_roles_table.sql
-- Description: Create roles table in chat schema
-- =====================================================

-- Create roles table
CREATE TABLE IF NOT EXISTS chat.roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP WITH TIME ZONE NULL,
    deleted_at TIMESTAMP WITH TIME ZONE NULL
);

-- Seed initial roles
INSERT INTO chat.roles (id, name)
VALUES
    (1, 'CUSTOMER'),
    (2, 'SPECIALIST'),
    (3, 'SUPER_ADMIN')
ON CONFLICT (name) DO NOTHING;

-- Create index
CREATE INDEX idx_roles_name ON chat.roles(name);

-- Add comment
COMMENT ON TABLE chat.roles IS 'User roles in chat system';