-- =====================================================
-- Migration: V4__create_message_attachments_table.sql
-- Description: Create message attachments table
-- =====================================================

-- Create message_attachments table
CREATE TABLE IF NOT EXISTS chat.message_attachments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id INT NOT NULL,
    file_url VARCHAR(500) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_type VARCHAR(100) NULL,
    file_size BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),

    -- Foreign key constraint
    CONSTRAINT fk_message_attachments_message FOREIGN KEY (message_id)
        REFERENCES chat.messages(id) ON DELETE CASCADE
);

-- Create index
CREATE INDEX idx_message_attachments_message_id ON chat.message_attachments(message_id);

-- Add comment
COMMENT ON TABLE chat.message_attachments IS 'Stores file attachments for messages';