-- =====================================================
-- Migration: V6__create_conversation_unread_count_table.sql
-- Description: Create unread message count tracking table
-- =====================================================

-- Create conversation_unread_count table (for performance optimization)
CREATE TABLE IF NOT EXISTS chat.conversation_unread_count (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id INT NOT NULL,
    user_id INT NOT NULL,
    unread_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP WITH TIME ZONE NULL,

    -- Foreign key constraints
    CONSTRAINT fk_conversation_unread_conversation FOREIGN KEY (conversation_id)
        REFERENCES chat.conversations(id) ON DELETE CASCADE,
    CONSTRAINT fk_conversation_unread_user FOREIGN KEY (user_id)
        REFERENCES chat.users(id) ON DELETE CASCADE,

    -- Unique constraint to prevent duplicate records
    CONSTRAINT uq_conversation_user_unread UNIQUE (conversation_id, user_id)
);

-- Create indexes
CREATE INDEX idx_conversation_unread_conversation_id ON chat.conversation_unread_count(conversation_id);
CREATE INDEX idx_conversation_unread_user_id ON chat.conversation_unread_count(user_id);
CREATE INDEX idx_conversation_unread_count_value ON chat.conversation_unread_count(unread_count) WHERE unread_count > 0;

-- Add comment
COMMENT ON TABLE chat.conversation_unread_count IS 'Caches unread message counts for performance';